[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
